apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
  labels:
    app: flask-app
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: us-central1-docker.pkg.dev/cloudops-gcp/apps/flask-app:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "256m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: flask-app-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
